- name: conditions in ansible
  hosts: local
  connection: local
  vars:
   NUM: 9
  tasks:
  - name: printing number if it's less or greater than ten
    ansible.builtin.debug:
     msg: {{ NUM }} is less than 10
    when: NUM < 10