- name: data types
  hosts: local
  connection: local
  vars:
   COURSE: Devops
   DURATION: 5
   is_true: yes
   tools:
   - shell
   - nginx
   - ansible
   concepts:
   cloud: aws
   cm: ansible
   tasks:
   - name: prints different variable types
     ansible.builtin.debug:
      msg: Course is {{ COURSE }} which is of {{ DURATION }} hours and is ongoing? - {{ is_true }}. We learn different tools like {{ tools }} and concepts like {{ concepts }}