- name: Prompt input from user
  hosts: my_ip
  connection: local
  vars_promt:
  - name: username
    prompt: Enter username
    private: no
  - name: password
    prompt: Enter password 
    private: yes

  tasks:
  - name: Print username and password
    ansible.builtin.debug:
     msg: Username is {{ username }} and password is {{ password }}